source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
platform :ios, '10.0'

target 'SBTUITestTunnel_Example' do
  pod 'SBTUITestTunnel', :path => '../'
end

abstract_target 'Tests' do
  pod 'SBTUITestTunnel', :path => '../'
  pod 'GCDWebServer', :git=> 'https://github.com/tcamin/GCDWebServer.git'
  pod 'SBTUITestTunnel', :path => '../'

  target 'SBTUITestTunnel_Tests' do
  end

  target 'SBTUITestTunnel_TestsNoSwizzling' do
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.name == 'Debug' or config.name == 'Release'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'ENABLE_UITUNNEL=1']
      end
    end
  end
end
